# Generated by Django 5.2.4 on 2025-07-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchslot',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='instructorslot',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AlterField(
            model_name='batchtime',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='cms.batch'),
        ),
        migrations.AlterField(
            model_name='batchtime',
            name='batch_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='cms.batchslot'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
