# Generated by Django 5.2.4 on 2025-07-07 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_image_remove_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.image'),
        ),
    ]
