# Generated by Django 5.2.4 on 2025-07-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='meeting_url',
        ),
    ]
